### ISSUE TITLE
"Manage Users" crash 

### ISSUE THREAD

**Issue by avp90** [CDRussell/Room#1]
If a Task is assigned to a User, it crashes.

**Comment by CDRussell** [comment]
Can you provide any crash logs / error message you see?

What device / emulator are you using?

I'm not able to replicate this. Thanks.

**Comment by avp90** [comment]
Hi, I have already found the bug. It seems that Room need all columns in Query (see pull request).

**Comment by CDRussell** [comment]
Thanks for that. I'd like to be able to replicate it first, but the existing code does not crash for me.

So I'd like more information about why it is crashing for you to understand the difference.

If you can provide device information, OS version etc... That would be a great help.

**Comment by avp90** [comment]
Hello @CDRussell, sorry for my late answer.

I tested it on my Motorola Z2 force (XT1789-06) with Android 8.0.0.

In the PullRequest https://github.com/CDRussell/Room/pull/2 you can see, that i added only the missing columns `Task.creationDate as task_creationDate, Task.notes as task_notes` to the query.
It seems that Room needs all columns in a Query to fetch the model.

**Comment by CDRussell** [comment]
Thanks for the extra info. I'll see if it's still happening on the latest Room version and merge if it's still a problem. Thanks!

**Comment by JYSerrano** [comment]
Hi @CDRussell 

I've ended up with your Room Course and I've faced the same problem that @avp90 .

This it's the error that ti's happening in the new room version:

![error](https://user-images.githubusercontent.com/24799624/55210760-c1023580-51c7-11e9-96eb-327129cd1173.png)


Now we need to indicate all the columns that we want to retrieve, if we don't want to do this we need to declare the fields as null.

So this is the two fixes for  this problem and I've already tested and work with both.

I guess that you can create a note for the new users that don't use the github frequently. showing this workaround for them.

I hope that I've helped with this info :)

Technical information:

Device: Nexus 6
Room Version: 1.1.1

**Comment by CDRussell** [comment]
Thanks for reporting this @avp90 and creating the PR, and for the extra info @JYSerrano. I was able to replicate the crash so I've merged that now.

I'll update the appropriate lesson when I can.
